repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:     
      - id: autopep8
  - repo: https://github.com/pycqa/flake8
    rev: v6.1.0
    hooks:
      - id: flake8
